name: PR Format and Lint (Rust)

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  format-and-lint-check:
    name: format-and-lint-check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust 1.89.0 (with rustfmt and clippy)
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.89.0
          components: rustfmt, clippy

      - name: Run rustfmt (check)
        run: cargo fmt --all -- --check

      - name: Run clippy (deny warnings)
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install lizard
        run: pip install --disable-pip-version-check --no-input lizard

      - name: Run lizard on main Lambda file only
        run: |
          # Check only the main file and fail on warnings
          # -C: cyclomatic complexity threshold (warn if function > 10)
          # -L: maximum function length (lines) threshold (warn if function > 120)
          lizard -l rust -C 10 -L 120 src/main.rs
          
      - name: Lizard csv output
        run: |
          lizard -l rust -C 10 -L 120 src/main.rs --csv          
